# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumberResultGlucose = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberResultGlucose.setGeometry(QtCore.QRect(30, 280, 91, 51))
        self.lcdNumberResultGlucose.setObjectName("lcdNumberResultGlucose")
        self.lineEditGlucose = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGlucose.setGeometry(QtCore.QRect(30, 50, 101, 21))
        self.lineEditGlucose.setObjectName("lineEditGlucose")
        self.comboBoxHR = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxHR.setGeometry(QtCore.QRect(30, 110, 101, 22))
        self.comboBoxHR.setObjectName("comboBoxHR")
        self.comboBoxDuration = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDuration.setGeometry(QtCore.QRect(30, 170, 101, 22))
        self.comboBoxDuration.setObjectName("comboBoxDuration")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonSimulate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSimulate.setGeometry(QtCore.QRect(30, 210, 93, 28))
        self.pushButtonSimulate.setObjectName("pushButtonSimulate")
        self.ImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageLabel.setGeometry(QtCore.QRect(220, 30, 640, 480))
        self.ImageLabel.setMinimumSize(QtCore.QSize(56, 16))
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TrainingCalculator"))
        self.label.setText(_translate("MainWindow", "Уровень глюкозы:"))
        self.label_2.setText(_translate("MainWindow", "Интенсивность тренировки:"))
        self.label_3.setText(_translate("MainWindow", "Длительность тренировки:"))
        self.pushButtonSimulate.setText(_translate("MainWindow", "Рассчитать"))
        self.label_4.setText(_translate("MainWindow", "Итоговая глюкоза:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
